fix: Fix `guard` issues (#297)
## Context

There's two issues currently when using guard:

1. The Docker image doesn't include `libffi` which causes the Docker build to fail:

    ````sh
    usr/local/bundle/gems/ffi-1.17.2/ext/ffi_c/libffi/src/tramp.c:55:10: fatal
    error: linux/limits.h: No such file or directory
       55 | #include <linux/limits.h>
          |          ^~~~~~~~~~~~~~~~
    compilation terminated.
    make[3]: *** [Makefile:1328: src/tramp.lo] Error 1
    make[3]: Leaving directory
    '/usr/local/bundle/gems/ffi-1.17.2/ext/ffi_c/libffi-aarch64-linux-musl'
    make[2]: *** [Makefile:1400: all-recursive] Error 1
    make[2]: Leaving directory
    '/usr/local/bundle/gems/ffi-1.17.2/ext/ffi_c/libffi-aarch64-linux-musl'
    make[1]: *** [Makefile:628: all] Error 2
    make[1]: Leaving directory
    '/usr/local/bundle/gems/ffi-1.17.2/ext/ffi_c/libffi-aarch64-linux-musl'
    make: *** [libffi.mk:9:
    "/usr/local/bundle/gems/ffi-1.17.2/ext/ffi_c/libffi-aarch64-linux-musl"/.libs/libffi_convenience.a]
    Error 2
    
    make failed, exit code 2
    
    Gem files will remain installed in /usr/local/bundle/gems/ffi-1.17.2 for
    inspection.
    Results logged to
    /usr/local/bundle/extensions/aarch64-linux-musl/3.4.0/ffi-1.17.2/gem_make.out
    
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:125:in 'Gem::Ext::Builder.run'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:51:in 'block in Gem::Ext::Builder.make'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:43:in 'Array#each'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:43:in 'Gem::Ext::Builder.make'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/ext_conf_builder.rb:44:in 'Gem::Ext::ExtConfBuilder.build'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:206:in 'Gem::Ext::Builder#build_extension'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:240:in 'block in Gem::Ext::Builder#build_extensions'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:237:in 'Array#each'
    /usr/local/lib/ruby/3.4.0/rubygems/ext/builder.rb:237:in 'Gem::Ext::Builder#build_extensions'
    /usr/local/lib/ruby/3.4.0/rubygems/installer.rb:844:in 'Gem::Installer#build_extensions'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:72:in 'Bundler::RubyGemsGemInstaller#build_extensions'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:28:in 'Bundler::RubyGemsGemInstaller#install'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in 'Bundler::Source::Rubygems#install'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in 'Bundler::GemInstaller#install'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in 'Bundler::GemInstaller#install_from_spec'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in 'Bundler::ParallelInstaller#do_install'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in 'block in Bundler::ParallelInstaller#worker_pool'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in 'Bundler::Worker#apply_func'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in 'block in Bundler::Worker#process_queue'
    <internal:kernel>:168:in 'Kernel#loop'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in 'Bundler::Worker#process_queue'
    /usr/local/bundle/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in 'block (2 levels) in Bundler::Worker#create_threads'
    
    An error occurred while installing ffi (1.17.2), and Bundler cannot continue.
    
    In Gemfile:
      guard-rspec was resolved to 4.7.3, which depends on
        guard was resolved to 2.19.1, which depends on
          listen was resolved to 3.9.0, which depends on
            rb-inotify was resolved to 0.11.1, which depends on
          ffi
    ````

2. We rely on an older version of `reline` which causes an error when exiting `guard`:

    ````sh
    /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:881:in 'block in Reline::LineEditor#clear_dialog': stack level too deep (SystemStackError)
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:880:in 'Array#each'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:880:in 'Reline::LineEditor#clear_dialog'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:223:in 'block in Reline::LineEditor#set_signal_handlers'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:239:in 'block in Reline::LineEditor#set_signal_handlers'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:239:in 'block in Reline::LineEditor#set_signal_handlers'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:239:in 'block in Reline::LineEditor#set_signal_handlers'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:239:in 'block in Reline::LineEditor#set_signal_handlers'
            from /usr/local/bundle/gems/reline-0.3.3/lib/reline/line_editor.rb:239:in 'block in Reline::LineEditor#set_signal_handlers'
             ... 13086 levels...
            from /usr/local/bundle/gems/thor-1.4.0/lib/thor/base.rb:584:in 'Thor::Base::ClassMethods#start'
            from /usr/local/bundle/gems/guard-2.19.1/lib/guard/aruba_adapter.rb:32:in 'Guard::ArubaAdapter#execute'
            from /usr/local/bundle/gems/guard-2.19.1/lib/guard/aruba_adapter.rb:19:in 'Guard::ArubaAdapter#execute!'
            from /usr/local/bundle/gems/guard-2.19.1/bin/_guard-core:11:in '<main>'
    ````

## Description

This fixes those issues by adding the `linux-headers` package in the Docker image and updating `reline` via `bundle update reline`.